-- ============================================================
--  CHAT_HISTORY : 사용자-AI 대화 기록 테이블
-- ------------------------------------------------------------
--  사용자 질문과 AI 답변을 일정/단계별로 저장하고, 일정 번호로 다시 조회한다.
--  실행: SQL*Plus / SQL Developer 에서 @migration_chat_history.sql
--  (재실행 시 아래 DROP 주석 해제)
-- ============================================================

-- DROP TABLE CHAT_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE CHAT_HISTORY (
    message_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 대화 한 줄의 번호
    guardian_id  VARCHAR2(50)   NOT NULL,   -- 보호자 아이디 (NUNGIL_USER.id)
    user_idx     NUMBER         NOT NULL,   -- 사용자 번호 (NUNGIL_USER.idx)
    schedule_id  NUMBER,                    -- 관련 일정 번호 (GENERAL 대화면 NULL)
    step_index   NUMBER,                    -- 대화가 발생한 단계 (없으면 NULL)
    chat_mode    VARCHAR2(20)   NOT NULL,   -- 'GENERAL' | 'SCHEDULE'
    sender       VARCHAR2(20)   NOT NULL,   -- 'USER' | 'ASSISTANT' | 'SYSTEM'
    message      VARCHAR2(2000) NOT NULL,   -- 실제 대화 내용
    intent       VARCHAR2(50),              -- 사용자 말의 목적 (없으면 NULL)
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP  -- 발생 시간
);

CREATE INDEX idx_chat_history_schedule
    ON CHAT_HISTORY (guardian_id, user_idx, schedule_id, created_at);

COMMIT;
