-- ============================================================
--  눈길(Nungil) 데이터베이스 스키마 (Oracle 12c 이상)
-- ============================================================
--  실행 순서:
--    1) schema.sql   ← 테이블 생성 (이 파일)
--    2) seed_data.sql ← 시연용 기본 데이터(과업 8건 등) 입력
--
--  실행 방법 (SQL*Plus / SQL Developer):
--    @schema.sql
--    @seed_data.sql
--    COMMIT;
--
--  ⚠️ 이미 테이블이 있으면 아래 DROP 블록의 주석을 풀어 초기화 후 실행하세요.
-- ============================================================

-- ─── (선택) 초기화 — 재실행 시 주석 해제 ───────────────────
-- DROP TABLE SCHEDULE      CASCADE CONSTRAINTS;
-- DROP TABLE NUNGIL_USER   CASCADE CONSTRAINTS;
-- DROP TABLE GUARDIAN      CASCADE CONSTRAINTS;
-- DROP TABLE TASK          CASCADE CONSTRAINTS;

-- ─── TASK : 과업 마스터 ────────────────────────────────────
--  기본 단계 가이드를 담는 마스터 테이블 (손 씻기, 양치질 등)
CREATE TABLE TASK (
    task_id   NUMBER          PRIMARY KEY,          -- 과업 번호
    name      VARCHAR2(100)   NOT NULL,             -- 과업 이름
    process   CLOB                                  -- 기본 단계 (JSON 배열 문자열)
);

-- ─── GUARDIAN : 보호자 계정 ────────────────────────────────
CREATE TABLE GUARDIAN (
    id         VARCHAR2(50)   PRIMARY KEY,          -- 로그인 아이디
    pw         VARCHAR2(255)  NOT NULL,             -- 비밀번호
    email      VARCHAR2(100),
    phone      VARCHAR2(20),
    name       VARCHAR2(50),
    fcm_token  VARCHAR2(255),                       -- 푸시 토큰
    regdate    DATE           DEFAULT SYSDATE       -- 가입일
);

-- ─── NUNGIL_USER : 보호자별 사용자(지적장애인) ─────────────
--  한 보호자(id)가 여러 사용자(idx)를 둘 수 있는 1:N 구조.
--  복합 기본키 (id, idx). idx는 보호자별로 1부터 채번.
CREATE TABLE NUNGIL_USER (
    id            VARCHAR2(50)  NOT NULL,           -- GUARDIAN.id 참조
    idx           NUMBER        NOT NULL,           -- 보호자별 사용자 번호
    special_note  CLOB,                             -- 특이사항 (프롬프트 반영)
    white_list    CLOB,                             -- 허용 과업 목록
    user_name     VARCHAR2(50),
    user_phone    VARCHAR2(20),
    fcm_token     VARCHAR2(255),
    CONSTRAINT pk_nungil_user   PRIMARY KEY (id, idx),
    CONSTRAINT fk_user_guardian FOREIGN KEY (id) REFERENCES GUARDIAN(id)
);

-- ─── SCHEDULE : 일정 ───────────────────────────────────────
--  schedule_id는 자동 채번(IDENTITY). 상태는 pending/completed/abandoned.
CREATE TABLE SCHEDULE (
    schedule_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id           NUMBER,                       -- TASK 참조
    id                VARCHAR2(50)  NOT NULL,       -- 사용자 소유 보호자 id
    idx               NUMBER        NOT NULL,       -- 사용자 idx
    status            VARCHAR2(20)  DEFAULT 'pending',
    scheduled_at      DATE,                         -- 예정 시각
    created_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    success_at        TIMESTAMP,                    -- 완료 시각
    location          VARCHAR2(200),                -- 장소
    special_note      VARCHAR2(1000),               -- 일정별 특이사항
    custom_steps      CLOB,                         -- AI 생성 맞춤 단계 (JSON)
    question_count    NUMBER        DEFAULT 0,      -- 수행 중 질문 횟수
    last_question_at  TIMESTAMP,                    -- 마지막 질문 시각
    CONSTRAINT fk_sched_task FOREIGN KEY (task_id)     REFERENCES TASK(task_id),
    CONSTRAINT fk_sched_user FOREIGN KEY (id, idx)     REFERENCES NUNGIL_USER(id, idx)
);

-- 조회 성능용 인덱스
CREATE INDEX idx_schedule_user ON SCHEDULE (id, idx);
CREATE INDEX idx_schedule_time ON SCHEDULE (scheduled_at);

COMMIT;
